version: "3.7"

services:
  eregold-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    container_name: eregold-backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
    networks:
      - eregold-network

  eregold-db:
    image: postgres:14.0-alpine
    container_name: eregold-db
    environment:
      POSTGRES_DB: eregold_db
      POSTGRES_USER: eregold_user
      POSTGRES_PASSWORD: eregold_pass
    ports:
      - "2345:5432"
    volumes:
      - ./database/data-dump/volume:/var/lib/postgresql/data/
    networks:
      - eregold-network

  eregold-db-migration:
    build:
      context: ./database/schema
      dockerfile: database/schema/Dockerfile-dev
      network: host
    container_name: eregold-db-migration
    volumes:
      - ./database/schema:/temp
    entrypoint: ["mvn", "flyway:migrate"]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:2345" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    network_mode: "host"

networks:
  eregold-network:
    driver: bridge