spring:
  profiles:
    active: local
  session:
    store-type: none
server:
  port: 8099

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
  mapper-locations: classpath*:/mybatis/mappers/*Mapper.xml

---
spring:
  config:
    activate:
      on-profile: docker
arkenstone:
  datasource:
    transactions:
      url: jdbc:postgresql://arkenstone-transactions-db:5432/arkenstone_transactions_db
      username: arkenstone_user
      password: arkenstone_pass
      driver-class-name:
    accounts:
      url: jdbc:postgresql://arkenstone-accounts-db:5432/arkenstone_accounts_db
      username: arkenstone_user
      password: arkenstone_pass
      driver-class-name:
  kafka:
    url: arkenstone-kafka-broker:9092

  gateway:
    url: http://arkenstone-api-gateway:8081
---
spring:
  config:
    activate:
      on-profile: local

arkenstone:
  datasource:
    transactions:
      url: jdbc:postgresql://localhost:2348/arkenstone_transactions_db
      username: arkenstone_user
      password: arkenstone_pass
      driver-class-name:
    accounts:
      url: jdbc:postgresql://localhost:2346/arkenstone_accounts_db
      username: arkenstone_user
      password: arkenstone_pass
      driver-class-name:
  kafka:
    url: localhost:9092

  gateway:
    url: http://localhost:8081
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    type: org.springframework.jdbc.datasource.SimpleDriverDataSource
    url: jdbc:postgresql://localhost:2345/mock
    username: mock
    password: mock
    driver-class-name:

arkenstone:
  gateway:
    url: http://localhost:8081
  kafka:
    url: localhost:9092