version: "3.9"

services:
#  eregold-backend:
#    build: ./backend
#    container_name: eregold-backend
#    ports:
#      - 8080:8080
#    volumes:
#      - ./backend:/app
#    networks:
#      - eregold-network
#    depends_on:
#      - eregold-session
#
#  arkenstone:
#    build: ./middleware
#    container_name: arkenstone
#    ports:
#      - 8081:8081
#    volumes:
#      - ./middleware:/app
#    networks:
#      - eregold-network
#
#  eregold-frontend:
#    build: ./frontend
#    container_name: eregold-frontend
#    ports:
#      - 4200:4200
#    volumes:
#      - ./frontend:/app
#    networks:
#      - eregold-network
#
#  eregold-session:
#    image: redis:6.2-alpine
#    container_name: eregold-session
#    restart: always
#    ports:
#      - "6379:6379"
#    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
#    volumes:
#      - cache-volume:/data
#    networks:
#      - eregold-network

  eregold-users-db:
    image: postgres:14.0-alpine
    container_name: eregold-users-db
    environment:
      POSTGRES_DB: eregold_users_db
      POSTGRES_USER: eregold_user
      POSTGRES_PASSWORD: eregold_pass
    ports:
      - "2345:5432"
    volumes:
      - ./database/users/data-dump/volume:/var/lib/postgresql/data/
    networks:
      - eregold-network

  arkenstone-accounts-db:
    image: postgres:14.0-alpine
    container_name: arkenstone-accounts-db
    environment:
      POSTGRES_DB: arkenstone_accounts_db
      POSTGRES_USER: arkenstone_user
      POSTGRES_PASSWORD: arkenstone_pass
    ports:
      - "2346:5432"
    volumes:
      - ./database/accounts/data-dump/volume:/var/lib/postgresql/data/
    networks:
      - eregold-network

  arkenstone-customers-db:
    image: postgres:14.0-alpine
    container_name: arkenstone-customers-db
    environment:
      POSTGRES_DB: arkenstone_customers_db
      POSTGRES_USER: arkenstone_user
      POSTGRES_PASSWORD: arkenstone_pass
    ports:
      - "2347:5432"
    volumes:
      - ./database/customers/data-dump/volume:/var/lib/postgresql/data/
    networks:
      - eregold-network

  arkenstone-transactions-db:
    image: postgres:14.0-alpine
    container_name: arkenstone-transactions-db
    environment:
      POSTGRES_DB: arkenstone_transactions_db
      POSTGRES_USER: arkenstone_user
      POSTGRES_PASSWORD: arkenstone_pass
    ports:
      - "2348:5432"
    volumes:
      - ./database/transactions/data-dump/volume:/var/lib/postgresql/data/
    networks:
      - eregold-network

networks:
  eregold-network:
    driver: bridge

volumes:
  cache-volume:
    driver: local