FROM maven:3.9.5-amazoncorretto-11

WORKDIR /app

COPY . .

RUN --mount=type=cache,target=/root/.m2 mvn -f /app/pom.xml clean install

CMD java -jar ./target/arkenstone-accounts-service.jar --spring.profiles.active=docker