version: "3.7"

services:
  eregold-backend:
    build: ./backend
    container_name: eregold-backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
    networks:
      - eregold-network
    depends_on:
      - eregold-session

  arkenstone:
    build: ./middleware
    container_name: arkenstone
    ports:
      - 8081:8081
    volumes:
      - ./middleware:/app
    networks:
      - eregold-network

  eregold-frontend:
    build: ./frontend
    container_name: eregold-frontend
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/app
    networks:
      - eregold-network

  eregold-session:
    image: redis:6.2-alpine
    container_name: eregold-session
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache-volume:/data
    networks:
      - eregold-network

  eregold-users-db:
    image: postgres:14.0-alpine
    container_name: eregold-users-db
    environment:
      POSTGRES_DB: eregold_users_db
      POSTGRES_USER: eregold_user
      POSTGRES_PASSWORD: eregold_pass
    ports:
      - "2345:5432"
    volumes:
      - ./database/data-dump/users/volume:/var/lib/postgresql/data/
    networks:
      - eregold-network

  eregold-users-db-migration:
    build:
      context: ./database/schema/users
      dockerfile: Dockerfile-complete
      network: host
    container_name: eregold-users-db-migration
    volumes:
      - ./database/schema/users:/temp
    entrypoint: [ "mvn", "flyway:migrate" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:2345" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    network_mode: "host"

  eregold-core-banking-db:
    image: postgres:14.0-alpine
    container_name: eregold-core-banking-db
    environment:
      POSTGRES_DB: eregold_core_db
      POSTGRES_USER: eregold_user
      POSTGRES_PASSWORD: eregold_pass
    ports:
      - "2346:5432"
    volumes:
      - ./database/data-dump/core-banking/volume:/var/lib/postgresql/data/
    networks:
      - eregold-network

  eregold-core-banking-db-migration:
    build:
      context: ./database/schema/core-banking
      dockerfile: Dockerfile-complete
      network: host
    container_name: eregold-core-banking-db-migration
    volumes:
      - ./database/schema/core-banking:/temp
    entrypoint: [ "mvn", "flyway:migrate" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:2346" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    network_mode: "host"

networks:
  eregold-network:
    driver: bridge

volumes:
  cache-volume:
    driver: local