spring:
  profiles:
    active: local

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
  mapper-locations: classpath*:/mybatis/mappers/*Mapper.xml

---
spring:
  config:
    activate:
      on-profile: docker
  session:
    store-type: redis
spring.datasource:
  url: jdbc:postgresql://eregold-users-db:5432/eregold_users_db
  username: eregold_user
  password: eregold_pass
  driver-class-name:
spring.redis:
    host: eregold-session # Redis server host.
    password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81 # Login password of the redis server.
    port: 6379

arkenstone:
  url: http://arkenstone-api-gateway:8081

---
spring:
  config:
    activate:
      on-profile: local
  session:
    store-type: redis
spring.datasource:
  url: jdbc:postgresql://localhost:2345/eregold_users_db
  username: eregold_user
  password: eregold_pass
  driver-class-name:
spring.redis:
  host: localhost # Redis server host.
  password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81 # Login password of the redis server.
  port: 6379
arkenstone:
  url: http://localhost:8081
---
spring:
  config:
    activate:
      on-profile: test
  session:
    store-type: none

spring.datasource:
  url: jdbc:postgresql://localhost:2345/eregold_users_db
  username: eregold_user
  password: eregold_pass
  driver-class-name:

spring.redis:
  host: localhost # Redis server host.
  password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81 # Login password of the redis server.
  port: 6379

arkenstone:
  url: http://localhost:8081