version: "3.7"

services:
  eregold-frontend:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: eregold-frontend
    ports:
      - 4200:4200
    volumes:
      - .:/app